version: "3.8"

services:
    pps_pgdb:
        container_name: pps_pgdb
        image: postgres:buster
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data/
        env_file:
            - .env.keycloak
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - pps_docker_network
    pps_keycloak:
        container_name: pps_keycloak
        image: jboss/keycloak:latest
        restart: always
        env_file:
            - .env.keycloak
        ports:
            - "8888:8080"
        depends_on:
            pps_pgdb:
                condition: service_healthy
        networks:
            - pps_docker_network
networks:
    pps_docker_network:
        driver: bridge
volumes:
    db_data:
    pgadmin_data: